# Environment variables for the build process
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

# Install system dependencies (e.g., ffmpeg)
[apt]
pkgs = ["ffmpeg", "python3", "python3-pip", "python3-dev"]

# Setup phase to ensure Python and pip are installed
[phases.setup]
dependsOn = []
cmds = [
  "apt-get update",
  "apt-get install -y python3 python3-pip python3-dev",
  "pip3 install --upgrade pip"
]

# Install phase for Python dependencies
[phases.install]
dependsOn = ["setup"]
cmds = ["pip3 install -r requirements.txt"]

# Start command for the application
[start]
cmd = "python3 main.py"
