# nixpacks.toml

# Build işlemi için kullanılacak ortam değişkenleri.
# Buradan Python sürümünü doğru bir şekilde belirtebiliriz.
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

# Ortama kurulacak ek sistem kütüphaneleri (FFmpeg gibi).
[apt]
pkgs = ["ffmpeg"]

# Python kütüphanelerini requirements.txt'den kurar.
[phases.install]
cmds = ["pip install -r requirements.txt"]

# Botu başlatacak komut.
[start]
cmd = "python main.py"
