# nixpacks.toml

# --- Ortam Değişkenleri (Environment Variables) ---
# Build işlemi için kullanılacak ortam değişkenleri.
# Buradan Python sürümünü doğru bir şekilde belirtebiliriz.
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

# --- Sistem Paketleri (System Packages) ---
# Ortama kurulacak ek sistem kütüphaneleri (FFmpeg gibi).
[apt]
pkgs = ["ffmpeg"]

# --- Kurulum Aşaması (Build Phase) ---
# Python kütüphanelerini requirements.txt'den kurar.
[phases.install]
cmds = ["pip install -r requirements.txt"]

# --- Başlatma Aşaması (Start Phase) ---
# Botu başlatacak komut.
[start]
cmd = "python main.py"
